import fs from "node:fs/promises";
import path from "node:path";
import { BaseAgent } from "../base-agent.js";
import type { AgentInput, AgentResult } from "../types.js";
import type { BaseChatModel } from "@langchain/core/language_models/chat_models";
import { HumanMessage } from "@langchain/core/messages";
import { z } from "zod";
import { StitchClient } from "./stitch-client.js";
import { InteractiveLoop } from "../../orchestrator/interactive-loop.js";
import { extractAndParseJson } from "../../llm/json-parser.js";
import { STITCH_INTERACTIVE_PROMPT, STITCH_DESIGN_PROMPT } from "./prompts.js";
import { resolveProjectTarget, type ProjectTarget } from "./project-target.js";

/** Required design gate between planning and source generation. */
export class StitchAgent extends BaseAgent {
  constructor() {
    super({
      name: "Google Stitch Design Agent",
      phase: "stitch",
      description: "Generates and reviews required UI screens before source generation.",
    });
  }

  protected async execute(input: AgentInput, llm: BaseChatModel): Promise<AgentResult> {
    const client = new StitchClient();
    let url: string | undefined;
    let projectId: string | undefined;
    try {
      const plan = input.payload.technicalPlan as { hasFrontend?: boolean } | undefined;
      if (!plan || typeof input.payload.documentsPath !== "string")
        throw new Error("Missing approved planning documents for Stitch");
      const requirements = String(input.payload.approvedRequirements ?? input.payload.rawIdea ?? "");
      if (resolveProjectTarget(requirements, plan).platform === "none") {
        input.onMessage?.("agent:message", {
          phase: this.phase,
          message: "Planning identifies this as a project without a UI; Stitch is not applicable.",
        });
        return {
          success: true,
          data: {
            stitch: {
              status: "not_applicable",
              screens: [],
              reason: "Approved plan has no frontend",
            },
          },
        };
      }
      const docsPath = input.payload.documentsPath;
      const ui = await fs.readFile(path.join(docsPath, "UI_DESIGN.md"), "utf8");
      const prd = await fs.readFile(path.join(docsPath, "PRD.md"), "utf8");
      if (!ui.trim() || !prd.trim()) throw new Error("PRD.md and UI_DESIGN.md must not be empty");
      const target = resolveProjectTarget(requirements.trim() || prd, plan);
      const platformContext = `${target.evidence}\nRequired Stitch deviceType: ${target.deviceType}. ${target.platform === "mobile" ? "Design a native mobile application: touch targets, safe areas, mobile navigation, keyboard and loading/error/empty states. Honor the selected client framework." : "Design a responsive browser website: desktop navigation, wide-screen information hierarchy and responsive small-screen behavior. Do not substitute a phone app mockup for the website."}\nThis target overrides conflicting platform suggestions in earlier design documents.`;
      input.onMessage?.("agent:message", {
        phase: this.phase,
        message: "Connecting to Google Stitch. Source generation will wait for completed designs.",
      });
      await client.connect();
      let savedProject: { projectId: string } | undefined;
      try {
        savedProject = JSON.parse(
          await fs.readFile(path.join(docsPath, "STITCH_PROJECT.json"), "utf8"),
        );
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
      }
      if (savedProject) input.payload.stitchProjectId = savedProject.projectId;
      const resuming = input.payload.resumeStitch === true || !!savedProject;
      if (resuming && typeof input.payload.stitchProjectId !== "string")
        throw new Error(
          "Missing saved Stitch project ID; refusing to create a replacement project",
        );
      const project = resuming
        ? await client.openProject(input.payload.stitchProjectId as string)
        : await client.createProject(`loom_${input.projectId.slice(0, 8)}`, "Generated by Loom");
      projectId = project.projectId;
      url = project.url;
      // Preserve a recoverable remote project link even if later generation fails.
      await fs.writeFile(
        path.join(docsPath, "STITCH_PROJECT.json"),
        JSON.stringify(project, null, 2),
      );
      input.onMessage?.("agent:message", { phase: this.phase, message: `Stitch project: ${url}` });
      await client.createDesignSystem(projectId, ui);
      const context = `${platformContext}\nApproved PRD: ${prd}\nDesign guidance: ${ui}\nAuthoritative user requirements: ${requirements}\n${platformContext}`;
      const generationWarning = resuming
        ? "Existing screens loaded. Review them and request any missing screens; no generation requests have been replayed."
        : await this.generateRequiredScreens(projectId, context, llm, client, input, target);
      if (generationWarning && !input.interactive) throw new Error(generationWarning);
      const result = await this.runInteractiveStitchLoop(
        input,
        projectId,
        url,
        llm,
        context,
        client,
        generationWarning,
        target,
      );
      if (!result.success) throw new Error("Stitch review ended without approval");
      const screens = await client.listScreens(projectId);
      if (!screens.length) throw new Error("Stitch returned no completed screens");
      const stitch = {
        status: input.interactive ? "approved" : "completed",
        projectId,
        url,
        screens,
        target,
      };
      await fs.writeFile(
        path.join(docsPath, "STITCH_RESULT.json"),
        JSON.stringify(stitch, null, 2),
      );
      return { success: true, data: { stitch, stitchUrl: url }, chatHistory: result.chatHistory };
    } catch (error) {
      const message = `Google Stitch phase failed: ${String(error)}. Source code generation has NOT started.`;
      input.onMessage?.("agent:message", { phase: this.phase, message });
      return {
        success: false,
        error: message,
        data: {
          stitch: { status: "failed", projectId, url, screens: [], error: String(error) },
          stitchUrl: url ?? null,
        },
      };
    } finally {
      await client
        .disconnect()
        .catch((error) => this.log.warn({ error: String(error) }, "Stitch cleanup failed"));
    }
  }

  private async runInteractiveStitchLoop(
    input: AgentInput,
    stitchProjectId: string,
    stitchUrl: string,
    llm: BaseChatModel,
    designContext: string,
    stitchClient: StitchClient,
    generationWarning: string | null,
    target: ProjectTarget,
  ): Promise<{ success: boolean; chatHistory?: import("../types.js").ChatMessage[] }> {
    if (!input.interactive) return { success: true };
    if (!input.waitForUserInput)
      throw new Error("Stitch review needs user input before code generation.");
    let actionError: string | null = null;

    const initialMessage = `
Your Google Stitch project is ready for review.
${generationWarning ? `⚠️ ${generationWarning}` : ""}

🔗 **View your designs live here:** ${stitchUrl}

Please review the screens in your browser.
If you want any changes (e.g., "Change the dashboard to a dark theme", "Move the nav bar to the left side"), just tell me!
I will update the designs in real-time.

When you are completely satisfied with how it looks, type **"approve"** and I will begin writing the full source code for the project.
`;

    const interactivePrompt = STITCH_INTERACTIVE_PROMPT.replace("{stitchUrl}", stitchUrl).replace(
      "{screensSummary}",
      `${JSON.stringify(await stitchClient.listScreens(stitchProjectId))}\nApproved requirements: ${designContext}`,
    );

    const loop = new InteractiveLoop();

    const result = await loop.run({
      initialHistory: input.resumeChatHistory,
      agentName: "UI/UX Architect",
      phase: "stitch",
      projectId: input.projectId,
      systemPrompt: interactivePrompt,
      initialAgentMessage: initialMessage,
      onMessage: input.onMessage,
      waitForUserInput: input.waitForUserInput,
      llm,
      maxTurns: 30,
      extractFinalOutput: false,
      beforeApprove: async () => {
        try {
          const screens = await stitchClient.listScreens(stitchProjectId);
          if (screens.length && actionError) {
            input.onMessage?.("agent:message", {
              phase: "stitch",
              message: `Approving the currently available designs as requested. The earlier request failed (${actionError}); this approval does not claim that request succeeded.`,
            });
            actionError = null;
          }
          return screens.length
            ? null
            : "No screens are listed yet. Check the Stitch project, request missing screens, or try approve again after generation finishes.";
        } catch (error) {
          return `Could not verify the designs: ${String(error)}. Please try approving again.`;
        }
      },
      // Intercept messages to apply MCP calls transparently
      onCustomAction: async (userMessage, _chatHistory, intent) => {
        if (intent === "question") return null;
        try {
          if (input.onMessage)
            input.onMessage("agent:message", {
              phase: "stitch",
              message: `🔄 Updating Stitch designs based on your feedback...`,
            });

          if (/page not found|404|url|link.*(?:broken|open)/i.test(userMessage)) {
            return `This is a Stitch access problem, not a design edit. Open ${stitchUrl} while signed into the account that owns the API key. No screen content was changed.`;
          }
          if (/generate|add|create|missing/i.test(userMessage)) {
            await stitchClient.generateScreens(
              stitchProjectId,
              `Create the separate screen(s) explicitly requested below. Preserve existing screens; do not redesign unrelated screens.\nUser request: ${userMessage}\nApproved project context: ${designContext}`,
              target.deviceType,
            );
            actionError = null;
            return "Stitch finished the requested generation call. Refresh the project and review the new screen before approving.";
          }
          // 1. Get current screens
          const screens = await stitchClient.listScreens(stitchProjectId);

          // 2. Use LLM to translate user intent to Stitch instruction
          const instructionPrompt = STITCH_DESIGN_PROMPT.replace("{feedback}", userMessage).replace(
            "{screensContext}",
            JSON.stringify(screens),
          );

          const instResponse = await llm.invoke([new HumanMessage(`${instructionPrompt}\nApproved project context: ${designContext}`)]);
          const instruction = String(instResponse.content);

          // Apply feedback to the current screens.

          if (screens.length > 0) {
            for (const screen of screens)
              await stitchClient.refineScreen(stitchProjectId, screen.id, `${instruction}\nApproved project context: ${designContext}`);
            actionError = null;
            return `I have updated the design with: "${instruction}". Please refresh the Stitch URL to see the changes.`;
          }
          throw new Error("No screens are available to update");
        } catch (error) {
          this.log.error({ error }, "Error refining stitch screen");
          actionError = String(error);
          return `Stitch design update failed: ${actionError}. You can retry the change, or review the existing screens and type approve to accept those designs.`;
        }
      },
    });

    if (actionError) throw new Error(actionError);
    return { success: result.approved, chatHistory: result.chatHistory };
  }

  private async generateRequiredScreens(
    projectId: string,
    context: string,
    llm: BaseChatModel,
    stitchClient: StitchClient,
    input: AgentInput,
    target: ProjectTarget,
  ): Promise<string | null> {
    const existing = await stitchClient.listScreens(projectId);
    const response = await llm.invoke([
      new HumanMessage(
        `List every required UI screen missing from this project, based on the approved requirements. No generic invented Home/Profile screens. Return JSON {"screens":[{"name":"name","prompt":"complete design instructions"}]}.\nRequirements: ${context}\nExisting screens: ${JSON.stringify(existing)}`,
      ),
    ]);
    const plan = z
      .object({ screens: z.array(z.object({ name: z.string(), prompt: z.string() })).max(30) })
      .parse(extractAndParseJson(String(response.content)));
    if (!existing.length && !plan.screens.length) throw new Error("No UI screens identified");
    for (const [index, screen] of plan.screens.entries()) {
      input.onMessage?.("agent:message", {
        phase: this.phase,
        message: `Generating design ${index + 1}/${plan.screens.length}: ${screen.name}`,
      });
      await stitchClient.generateScreens(projectId, `${screen.name}: ${screen.prompt}\nApproved project context: ${context}`, target.deviceType);
    }
    const screens = await stitchClient.listScreens(projectId);
    if (screens.length < existing.length + plan.screens.length)
      return `Stitch generation may be incomplete: ${screens.length} screen(s) are listed after ${plan.screens.length} request(s), with ${existing.length} previously listed. Review the project and ask for any missing screens. Approve only when the designs meet your requirements.`;
    return null;
  }
}

new StitchAgent();
